// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// em_e_step
List em_e_step(IntegerMatrix Y, NumericVector par_pre, NumericVector P_Z_pre, int N, int I, int L, int poly_max);
RcppExport SEXP _LCPA_em_e_step(SEXP YSEXP, SEXP par_preSEXP, SEXP P_Z_preSEXP, SEXP NSEXP, SEXP ISEXP, SEXP LSEXP, SEXP poly_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par_pre(par_preSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type P_Z_pre(P_Z_preSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type I(ISEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type poly_max(poly_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(em_e_step(Y, par_pre, P_Z_pre, N, I, L, poly_max));
    return rcpp_result_gen;
END_RCPP
}
// em_m_step
List em_m_step(NumericMatrix P_Z_Xn, NumericVector Y_hot, IntegerVector poly_value, int N, int I, int L, int poly_max);
RcppExport SEXP _LCPA_em_m_step(SEXP P_Z_XnSEXP, SEXP Y_hotSEXP, SEXP poly_valueSEXP, SEXP NSEXP, SEXP ISEXP, SEXP LSEXP, SEXP poly_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type P_Z_Xn(P_Z_XnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y_hot(Y_hotSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type poly_value(poly_valueSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type I(ISEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type poly_max(poly_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(em_m_step(P_Z_Xn, Y_hot, poly_value, N, I, L, poly_max));
    return rcpp_result_gen;
END_RCPP
}
// make_latent_paths_cpp
arma::umat make_latent_paths_cpp(int L, int times);
RcppExport SEXP _LCPA_make_latent_paths_cpp(SEXP LSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(make_latent_paths_cpp(L, times));
    return rcpp_result_gen;
END_RCPP
}
// lta_vector_to_parameters_cpp
List lta_vector_to_parameters_cpp(NumericVector params, List covariates_list, int L, int ref_class);
RcppExport SEXP _LCPA_lta_vector_to_parameters_cpp(SEXP paramsSEXP, SEXP covariates_listSEXP, SEXP LSEXP, SEXP ref_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< List >::type covariates_list(covariates_listSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type ref_class(ref_classSEXP);
    rcpp_result_gen = Rcpp::wrap(lta_vector_to_parameters_cpp(params, covariates_list, L, ref_class));
    return rcpp_result_gen;
END_RCPP
}
// get_log_lik_lta_optim_cpp
double get_log_lik_lta_optim_cpp(NumericVector init_par, List CEP_list, List Zs_list, List covariates_list, bool covariates_timeCross, int ref_class, arma::umat latent_paths);
RcppExport SEXP _LCPA_get_log_lik_lta_optim_cpp(SEXP init_parSEXP, SEXP CEP_listSEXP, SEXP Zs_listSEXP, SEXP covariates_listSEXP, SEXP covariates_timeCrossSEXP, SEXP ref_classSEXP, SEXP latent_pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type init_par(init_parSEXP);
    Rcpp::traits::input_parameter< List >::type CEP_list(CEP_listSEXP);
    Rcpp::traits::input_parameter< List >::type Zs_list(Zs_listSEXP);
    Rcpp::traits::input_parameter< List >::type covariates_list(covariates_listSEXP);
    Rcpp::traits::input_parameter< bool >::type covariates_timeCross(covariates_timeCrossSEXP);
    Rcpp::traits::input_parameter< int >::type ref_class(ref_classSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type latent_paths(latent_pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_log_lik_lta_optim_cpp(init_par, CEP_list, Zs_list, covariates_list, covariates_timeCross, ref_class, latent_paths));
    return rcpp_result_gen;
END_RCPP
}
// adjust_response_cpp
List adjust_response_cpp(NumericMatrix response);
RcppExport SEXP _LCPA_adjust_response_cpp(SEXP responseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type response(responseSEXP);
    rcpp_result_gen = Rcpp::wrap(adjust_response_cpp(response));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LCPA_em_e_step", (DL_FUNC) &_LCPA_em_e_step, 7},
    {"_LCPA_em_m_step", (DL_FUNC) &_LCPA_em_m_step, 7},
    {"_LCPA_make_latent_paths_cpp", (DL_FUNC) &_LCPA_make_latent_paths_cpp, 2},
    {"_LCPA_lta_vector_to_parameters_cpp", (DL_FUNC) &_LCPA_lta_vector_to_parameters_cpp, 4},
    {"_LCPA_get_log_lik_lta_optim_cpp", (DL_FUNC) &_LCPA_get_log_lik_lta_optim_cpp, 7},
    {"_LCPA_adjust_response_cpp", (DL_FUNC) &_LCPA_adjust_response_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_LCPA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
