# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em_e_step <- function(Y, par_pre, P_Z_pre, N, I, L, poly_max) {
    .Call(`_LCPA_em_e_step`, Y, par_pre, P_Z_pre, N, I, L, poly_max)
}

em_m_step <- function(P_Z_Xn, Y_hot, poly_value, N, I, L, poly_max) {
    .Call(`_LCPA_em_m_step`, P_Z_Xn, Y_hot, poly_value, N, I, L, poly_max)
}

make_latent_paths_cpp <- function(L, times) {
    .Call(`_LCPA_make_latent_paths_cpp`, L, times)
}

lta_vector_to_parameters_cpp <- function(params, covariates_list, L, ref_class) {
    .Call(`_LCPA_lta_vector_to_parameters_cpp`, params, covariates_list, L, ref_class)
}

get_log_lik_lta_optim_cpp <- function(init_par, CEP_list, Zs_list, covariates_list, covariates_timeCross, ref_class, latent_paths) {
    .Call(`_LCPA_get_log_lik_lta_optim_cpp`, init_par, CEP_list, Zs_list, covariates_list, covariates_timeCross, ref_class, latent_paths)
}

adjust_response_cpp <- function(response) {
    .Call(`_LCPA_adjust_response_cpp`, response)
}

