# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lca_expectation_cpp <- function(response, par, P_Z) {
    .Call(`_LCPA_lca_expectation_cpp`, response, par, P_Z)
}

lca_maximization_cpp <- function(response, posterior, poly_value, smoothing) {
    .Call(`_LCPA_lca_maximization_cpp`, response, posterior, poly_value, smoothing)
}

sample_lca_response_cpp <- function(classes, par, poly_value) {
    .Call(`_LCPA_sample_lca_response_cpp`, classes, par, poly_value)
}

lca_score_information_cpp <- function(response, par, P_Z, poly_value, compute_information) {
    .Call(`_LCPA_lca_score_information_cpp`, response, par, P_Z, poly_value, compute_information)
}

lpa_expectation_cpp <- function(response, means, covs, P_Z, repair) {
    .Call(`_LCPA_lpa_expectation_cpp`, response, means, covs, P_Z, repair)
}

mvn_log_density_cpp <- function(response, mean, covariance, repair) {
    .Call(`_LCPA_mvn_log_density_cpp`, response, mean, covariance, repair)
}

make_latent_paths_cpp <- function(L, times) {
    .Call(`_LCPA_make_latent_paths_cpp`, L, times)
}

lta_vector_to_parameters_cpp <- function(params, covariates_list, L, ref_class) {
    .Call(`_LCPA_lta_vector_to_parameters_cpp`, params, covariates_list, L, ref_class)
}

get_log_lik_lta_optim_cpp <- function(params, CEP_list, Zs_list, covariates_list, covariates_time_cross, ref_class, compute_gradient) {
    .Call(`_LCPA_get_log_lik_lta_optim_cpp`, params, CEP_list, Zs_list, covariates_list, covariates_time_cross, ref_class, compute_gradient)
}

sample_multinomial_logit_cpp <- function(covariates, coefficients) {
    .Call(`_LCPA_sample_multinomial_logit_cpp`, covariates, coefficients)
}

mean_multinomial_logit_probability_cpp <- function(covariates, coefficients) {
    .Call(`_LCPA_mean_multinomial_logit_probability_cpp`, covariates, coefficients)
}

sample_transition_logit_cpp <- function(previous, covariates, gamma) {
    .Call(`_LCPA_sample_transition_logit_cpp`, previous, covariates, gamma)
}

sample_markov_cpp <- function(previous, rate) {
    .Call(`_LCPA_sample_markov_cpp`, previous, rate)
}

adjust_response_cpp <- function(response) {
    .Call(`_LCPA_adjust_response_cpp`, response)
}

classification_error_counts_cpp <- function(posterior) {
    .Call(`_LCPA_classification_error_counts_cpp`, posterior)
}

bch_multinomial_cpp <- function(params, design, weight, ref_class, compute_gradient, compute_information) {
    .Call(`_LCPA_bch_multinomial_cpp`, params, design, weight, ref_class, compute_gradient, compute_information)
}

