#' @title S3 Methods: plot
#'
#' @description
#' Generates user-friendly, publication-ready visualizations for objects generated by the \code{LCPA} package.
#' This generic function dispatches to class-specific methods that produce diagnostic and interpretive plots
#' tailored to each model type. Designed for interactive exploration, model interpretation, and presentation-quality output.
#'
#' @param x An object of one of the following classes:
#'   \itemize{
#'     \item Model objects: \code{\link[LCPA]{LCA}}, \code{\link[LCPA]{LPA}}.
#'   }
#' @param ncol Number of columns in the multi-panel layout (default: 2).
#'   Controls arrangement of latent class/profile panels.
#' @param ... Additional arguments passed to methods.
#'
#' @return Invisibly returns the final \code{ggplot} or \code{patchwork} object. No data is modified.
#'
#' @details
#' Each method produces a structured, visually intuitive plot optimized for its object type.
#' See specific method documentation (\code{plot.LCA}, \code{plot.LPA}) for detailed parameter options.
#'
#' @name plot
NULL

#' @describeIn plot Plot method for \code{LCA} objects
#' @export
#' @importFrom ggplot2 ggplot aes geom_col scale_y_continuous labs theme_minimal theme element_text element_blank guide_legend guides unit
#' @importFrom dplyr %>%
#' @importFrom tidyr pivot_longer
#' @importFrom patchwork wrap_plots plot_layout plot_spacer
#' @importFrom scales percent_format
#'
plot.LCA <- function(x, ncol = 2, ...) {
  L <- dim(x$params$par)[1]
  I <- dim(x$params$par)[2]
  P.Z <- x$P.Z
  plots <- list()

  for (l in 1:L) {
    df <- as.data.frame(x$params$par[l, , ])
    colnames(df) <- paste0("Cat. ", as.integer(gsub("category\\.", "", colnames(df))))
    df$indicator <- 1:I
    df_long <- df %>%
      pivot_longer(
        cols = -indicator,
        names_to = "category",
        values_to = "probability"
      )

    indicator <- df_long$indicator
    category <- df_long$category
    probability <- df_long$probability

    p <- ggplot(df_long, aes(x = indicator, y = probability, fill = category)) +
      geom_bar(stat = "identity", position = position_fill(reverse = TRUE),
               width = 0.7, color = "white") +
      scale_x_continuous(breaks = scales::breaks_width(1)) +
      scale_y_continuous(labels = percent_format(accuracy = 1)) +
      labs(
        title = paste0("Class ", l, " (", sprintf("%.2f", P.Z[l] * 100), "%)"),
        x = "Indicator",
        y = "Probability (Cumulative)",
        fill = "Response\nCategories"
      ) +
      theme_minimal(base_size = 16) +
      theme(
        axis.text.x = element_text(angle = 0, hjust = 0.5),
        panel.grid.major.x = element_blank(),
        legend.position = "none",
        plot.margin = margin(4, 8, 2, 8),
        plot.title = element_text(size = 14, margin = margin(b = 4))
      )
    plots[[l]] <- p
  }

  df_first <- as.data.frame(x$params$par[1, , ])
  colnames(df_first) <- paste0("Cat. ", as.integer(gsub("category\\.", "", colnames(df_first))))
  df_first$indicator <- 1:I
  df_first_long <- df_first %>%
    pivot_longer(cols = -indicator, names_to = "category", values_to = "probability")

  df_legend <- data.frame(
    indicator = 1,
    category = unique(df_first_long$category),
    probability = 0
  )

  legend_plot <- ggplot(df_legend, aes(x = indicator, y = probability, fill = category)) +
    geom_col(alpha = 0) +
    labs(fill = "Response Categories") +
    theme_void() +
    theme(
      legend.position = "bottom",
      legend.direction = "horizontal",
      legend.box.margin = margin(t = 2, r = 0, b = 2, l = 0),
      legend.margin = margin(t = 0, b = 0, l = 0, r = 0),
      legend.spacing.x = unit(11, "pt"),
      legend.spacing.y = unit(0, "pt"),
      legend.key.size = unit(11, "pt"),
      legend.title = element_text(size = 12, face = "bold", margin = margin(r = 8)),
      legend.text = element_text(size = 12),
      plot.margin = margin(t = 0, r = 0, b = 0, l = 0)
    ) +
    guides(fill = guide_legend(
      nrow = 1,
      override.aes = list(alpha = 1),
      title.position = "top"
    ))

  main_plots <- wrap_plots(plots[1:L], ncol = ncol) +
    plot_layout(guides = "collect") &
    theme(
      plot.margin = margin(3, 6, 1, 6)
    )

  final_plot <- main_plots / legend_plot +
    plot_layout(
      heights = c(1, 0.0 + 0 * length(unique(df_legend$category)))
    )

  print(final_plot)
  invisible(final_plot)
}

#' @describeIn plot Plot method for \code{LPA} objects (with covariance heatmap)
#' @export
#'
#' @importFrom ggplot2 ggplot aes geom_ribbon geom_line geom_point scale_x_continuous labs theme_minimal theme element_text element_blank geom_tile scale_fill_gradient2
#' @importFrom dplyr %>%
#' @importFrom tidyr pivot_longer
#' @importFrom patchwork wrap_plots
#' @importFrom reshape2 melt
#' @importFrom scales squish
plot.LPA <- function(x, ncol = 2, ...) {

  means <- x$params$means
  covs  <- x$params$covs
  P.Z   <- x$params$P.Z

  L <- nrow(means)
  I <- ncol(means)

  indicator_names <- colnames(means)
  x_index <- 1:I

  plots <- list()

  global_max <- -Inf
  global_min <- Inf
  for(l in 1:L){
    Sigma <- covs[, , l]
    global_max <- max(max(Sigma, na.rm = TRUE), global_max)
    global_min <- min(min(Sigma, na.rm = TRUE), global_min)
    current_min <- global_min
    if (global_min > global_max) {
      temp <- global_min
      global_min <- global_max
      global_max <- temp
    }
    if(global_max < abs(global_min)){
      global_max <- -current_min
    }else{
      global_min <- -global_max
    }
    limit_high <- global_max * 0.90
    limit_low  <- global_min * 0.90
  }
  limits <- c(limit_low, limit_high)

  for (l in 1:L) {

    mu <- as.numeric(means[l, ])
    Sigma <- covs[, , l]
    sd <- sqrt(diag(Sigma))

    lower = mu - sd
    upper = mu + sd

    df <- data.frame(
      x = x_index,
      indicator = factor(indicator_names, levels = indicator_names),
      mean = mu,
      lower = mu - sd,
      upper = mu + sd
    )

    profile_plot <- ggplot(df, aes(x = x, y = mean, group = 1)) +

      geom_ribbon(aes(ymin = lower, ymax = upper),
                  fill = "#BDC3C7", alpha = 0.35) +

      geom_line(linewidth = 1.1, color = "#2C3E50") +
      geom_point(size = 2.3, color = "#2C3E50") +

      scale_x_continuous(
        breaks = x_index,
        labels = indicator_names
      ) +

      labs(
        title = paste0(
          "Profile ", l,
          " (", sprintf("%.1f%%", P.Z[l] * 100), ")"
        ),
        x = "Indicators",
        y = "Mean"
      ) +

      theme_minimal(base_size = 14) +
      theme(
        axis.text.x = element_text(angle = 90, hjust = 1),
        panel.grid.major.x = element_blank(),
        plot.title = element_text(size = 13)
      )

    cov_plot <- .make_cov_heatmap(
      Sigma = Sigma,
      indicator_names = indicator_names,
      class_id = l,
      prob = P.Z[l],
      limits = limits
    )

    combined <- profile_plot / cov_plot

    plots[[l]] <- combined
  }

  final_plot <- wrap_plots(plots, ncol = ncol)

  print(final_plot)
  invisible(final_plot)
}

.make_cov_heatmap <- function(Sigma, indicator_names, class_id, prob, limits = NULL) {

  df_cov <- reshape2::melt(Sigma)
  colnames(df_cov) <- c("Var1", "Var2", "value")

  Var1 <- df_cov$Var1
  Var2 <- df_cov$Var2
  value <- df_cov$value

  df_cov$Var1 <- factor(indicator_names[df_cov$Var1], levels = indicator_names)
  df_cov$Var2 <- factor(indicator_names[df_cov$Var2], levels = indicator_names)

  p <- ggplot(df_cov, aes(x = Var1, y = Var2, fill = value)) +
    geom_tile() +

    scale_fill_gradient2(
      low = "#2166AC",
      mid = "white",
      high = "#B2182B",
      midpoint = 0,
      limits = limits,
      oob = scales::squish
    ) +

    labs(
      title = paste0(
        "Covariance Matrix (Profile ", class_id,
        ", ", sprintf("%.1f%%", prob * 100), ")"
      ),

      x = NULL,
      y = NULL,
      fill = "Cov"
    ) +

    theme_minimal(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1, color = "black"),
      axis.text.y = element_text(color = "black"),
      panel.grid = element_blank(),
      plot.title = element_text(size = 11)
    )

  return(p)
}
