#' @title S3 Methods: update
#'
#' @description
#' The \code{update} function provides a unified and convenient interface to refresh or modify
#' existing objects generated by the \code{\link[LCPA]{LCPA}} package. It allows users to re-run model fitting
#' or data simulation with new parameter settings while preserving all other original configurations.
#' Supported classes include: \code{\link[LCPA]{LCA}}, \code{\link[LCPA]{LPA}},
#' \code{\link[LCPA]{LCPA}}, \code{\link[LCPA]{LTA}}, \code{\link[LCPA]{sim.LCA}},
#' \code{\link[LCPA]{sim.LPA}}, and \code{\link[LCPA]{sim.LTA}}.
#'
#' @param object An object of one of the following classes:
#'   \itemize{
#'     \item \code{\link[LCPA]{LCA}} — Latent Class Analysis model.
#'     \item \code{\link[LCPA]{LPA}} — Latent Profile Analysis model.
#'     \item \code{\link[LCPA]{LCPA}} — Latent Class Prediction Analysis (with covariates).
#'     \item \code{\link[LCPA]{LTA}} — Latent Transition Analysis model.
#'     \item \code{\link[LCPA]{sim.LCA}} — Simulated LCA dataset.
#'     \item \code{\link[LCPA]{sim.LPA}} — Simulated LPA dataset.
#'     \item \code{\link[LCPA]{sim.LTA}} — Simulated LTA dataset.
#'   }
#' @param ... Named arguments that override values in the original call.
#'   Every argument must be named, unique, and present in the formal arguments
#'   of the corresponding constructor. Valid arguments depend on the class of
#'   \code{object}:
#'   \describe{
#'     \item{\code{\link[LCPA]{LCA}}}{\code{response}, \code{L},
#'       \code{category.levels}, \code{method}, \code{par.ini}, \code{is.sort},
#'       \code{starts}, \code{maxiter.warmup}, \code{nrep}, \code{vis},
#'       \code{control.EM}, \code{control.Mplus}, \code{control.NNE},
#'       \code{control.flexmix}, \code{control.Rmixmod}, \code{control.RMixtComp}}
#'     \item{\code{\link[LCPA]{LPA}}}{\code{response}, \code{L},
#'       \code{constraint}, \code{method}, \code{par.ini}, \code{is.sort},
#'       \code{starts}, \code{maxiter.warmup}, \code{nrep}, \code{vis},
#'       \code{control.EM}, \code{control.Mplus}, \code{control.NNE},
#'       \code{control.flexmix}, \code{control.Rmixmod}, \code{control.RMixtComp}}
#'     \item{\code{\link[LCPA]{LCPA}}}{\code{response}, \code{L}, \code{type.analysis},
#'       \code{type.model}, \code{covariates}, \code{ref.class}, \code{dependent.variables},
#'       \code{family}, \code{method.model}, \code{control.model},
#'       \code{control.EM}, \code{control.Mplus}, \code{control.NNE},
#'       \code{control.flexmix}, \code{control.Rmixmod}, \code{control.RMixtComp},
#'       \code{method.3step}, \code{CEP.error}, \code{method.regression},
#'       \code{maxiter}, \code{tol}, \code{lower}, \code{upper}, \code{method.SE},
#'       \code{nrep.bootstrap}, \code{vis}}
#'     \item{\code{\link[LCPA]{LTA}}}{\code{responses}, \code{L}, \code{type.analysis},
#'       \code{type.model}, \code{covariates}, \code{covariates.time.cross},
#'       \code{ref.class}, \code{dependent.variables}, \code{family},
#'       \code{dependent.variable.structure}, \code{dependent.variable.time},
#'       \code{dependent.variable.time.cross},
#'       \code{method.model}, \code{step1.pool}, \code{control.model},
#'       \code{control.EM}, \code{control.Mplus}, \code{control.NNE},
#'       \code{control.Rmixmod}, \code{method.3step}, \code{CEP.error},
#'       \code{CEP.time.cross}, \code{method.regression}, \code{maxiter},
#'       \code{tol}, \code{lower}, \code{upper}, \code{method.SE},
#'       \code{nrep.bootstrap}, \code{vis}}
#'     \item{\code{\link[LCPA]{sim.LCA}}}{\code{N}, \code{I}, \code{L}, \code{poly.value}, \code{IQ},
#'       \code{distribution}, \code{params}, \code{is.sort}}
#'     \item{\code{\link[LCPA]{sim.LPA}}}{\code{N}, \code{I}, \code{L}, \code{constraint}, \code{distribution},
#'       \code{mean.range}, \code{covs.range}, \code{params}, \code{is.sort}}
#'     \item{\code{\link[LCPA]{sim.LTA}}}{\code{N}, \code{I}, \code{L},
#'       \code{times}, \code{type}, \code{distribution}, \code{constraint},
#'       \code{poly.value}, \code{IQ}, \code{mean.range}, \code{covs.range},
#'       \code{params}, \code{is.sort}, \code{rate}, \code{covariates},
#'       \code{ref.class}, \code{beta}, \code{gamma}}
#'   }
#'
#' @return An object of the same class as \code{object}, reconstructed using the original arguments
#'   updated with any provided in \code{...}. All unchanged parameters are preserved from the original call.
#'
#' @details
#' Internally, each method extracts the stored \code{arguments} list from the input object \code{object},
#' merges it with user-provided \code{...} using \code{\link[utils]{modifyList}}, then re-invokes
#' the corresponding constructor function (\code{\link[LCPA]{LCA}()},
#' \code{\link[LCPA]{LPA}()}, \code{\link[LCPA]{LCPA}()},
#' \code{\link[LCPA]{LTA}()}, \code{\link[LCPA]{sim.LCA}()}, etc.) with the
#' merged argument list.
#'
#' This ensures that:
#' \itemize{
#'   \item Only explicitly overridden parameters are changed.
#'   \item Default values from the original call remain intact.
#'   \item Complex nested structures (e.g., control lists) can be partially updated.
#' }
#'
#' Invalid, unnamed, or duplicated arguments are rejected before the
#' constructor is called. This prevents a misspelled option from appearing to
#' update an object while leaving the fitted model unchanged.
#'
#' @examples
#' \donttest{
#' library(LCPA)
#'
#' # --- Update LCA ---
#' data <- sim.LCA(N=500, I=5, L=3)
#' lca.obj <- LCA(data$response, L=3)
#' lca.updated <- update(lca.obj, method="EM", nrep=5)
#'
#' # --- Update LPA ---
#' data2 <- sim.LPA(N=300, I=4, L=2)
#' lpa.obj <- LPA(data2$response, L=2, constraint="VE")
#' lpa.updated <- update(lpa.obj, constraint="VV")
#'
#' # --- Update Simulation Objects ---
#' sim.obj1 <- sim.LCA(N=1000)
#' sim.obj1_updated <- update(sim.obj1, N=2000, IQ=0.8)
#'
#' sim.obj2 <- sim.LPA(I=6)
#' sim.obj2_updated <- update(sim.obj2, I=8, mean.range=c(-2,2))
#'
#' sim.obj3 <- sim.LTA(N=200, I=5, L=2, times=3)
#' sim.obj3_updated <- update(sim.obj3, N=300, times=4, constraint="ER")
#' }
#'
#' @name update
update <- function(object, ...) {
  UseMethod("update")
}

.update.arguments <- function(arguments.current, dots, constructor,
                              constructor.name) {
  if(!length(dots)) return(arguments.current)
  dot.names <- names(dots)
  if(is.null(dot.names) || any(!nzchar(dot.names))){
    stop("All update arguments must be named", call. = FALSE)
  }
  if(anyDuplicated(dot.names)){
    duplicated.names <- unique(dot.names[duplicated(dot.names)])
    stop(
      "Duplicated update argument(s): ",
      paste(duplicated.names, collapse = ", "),
      call. = FALSE
    )
  }
  unknown <- setdiff(dot.names, names(formals(constructor)))
  if(length(unknown)){
    stop(
      "Unknown argument(s) for ", constructor.name, "(): ",
      paste(unknown, collapse = ", "),
      call. = FALSE
    )
  }
  modifyList(arguments.current, dots)
}

#' @describeIn update Update method for \code{LCA} objects
#' @importFrom utils modifyList
#' @export
update.LCA <- function(object, ...) {
  arguments.current <- object$arguments
  arguments.new <- .update.arguments(
    arguments.current, list(...), LCA, "LCA"
  )

  LCA.updated <- LCA(
    response = arguments.new$response,
    L = arguments.new$L,
    category.levels = arguments.new$category.levels,
    method = arguments.new$method,
    par.ini = arguments.new$par.ini,
    is.sort = arguments.new$is.sort,
    starts = arguments.new$starts,
    maxiter.warmup = arguments.new$maxiter.warmup,
    nrep = arguments.new$nrep,
    vis = arguments.new$vis,
    control.EM = arguments.new$control.EM,
    control.Mplus = arguments.new$control.Mplus,
    control.NNE = arguments.new$control.NNE,
    control.flexmix = arguments.new$control.flexmix,
    control.Rmixmod = arguments.new$control.Rmixmod,
    control.RMixtComp = arguments.new$control.RMixtComp
  )
  return(LCA.updated)
}

#' @describeIn update Update method for \code{LPA} objects
#' @importFrom utils modifyList
#' @export
update.LPA <- function(object, ...) {
  arguments.current <- object$arguments
  arguments.new <- .update.arguments(
    arguments.current, list(...), LPA, "LPA"
  )

  LPA.updated <- LPA(
    response = arguments.new$response,
    L = arguments.new$L,
    constraint = arguments.new$constraint,
    method = arguments.new$method,
    par.ini = arguments.new$par.ini,
    is.sort = arguments.new$is.sort,
    starts = arguments.new$starts,
    maxiter.warmup = arguments.new$maxiter.warmup,
    nrep = arguments.new$nrep,
    vis = arguments.new$vis,
    control.EM = arguments.new$control.EM,
    control.Mplus = arguments.new$control.Mplus,
    control.NNE = arguments.new$control.NNE,
    control.flexmix = arguments.new$control.flexmix,
    control.Rmixmod = arguments.new$control.Rmixmod,
    control.RMixtComp = arguments.new$control.RMixtComp
  )
  return(LPA.updated)
}

#' @describeIn update Update method for \code{LCPA} objects
#' @importFrom utils modifyList
#' @export
update.LCPA <- function(object, ...) {
  arguments.current <- object$arguments
  arguments.new <- .update.arguments(
    arguments.current, list(...), LCPA, "LCPA"
  )

  LCPA.updated <- LCPA(
    response = arguments.new$response,
    L = arguments.new$L,
    type.analysis = arguments.new$type.analysis,
    type.model = arguments.new$type.model,
    covariates = arguments.new$covariates,
    ref.class = arguments.new$ref.class,
    dependent.variables = arguments.new$dependent.variables,
    family = arguments.new$family,
    method.model = arguments.new$method.model,
    control.model = arguments.new$control.model,
    control.EM = arguments.new$control.EM,
    control.Mplus = arguments.new$control.Mplus,
    control.NNE = arguments.new$control.NNE,
    control.flexmix = arguments.new$control.flexmix,
    control.Rmixmod = arguments.new$control.Rmixmod,
    control.RMixtComp = arguments.new$control.RMixtComp,
    method.3step = arguments.new$method.3step,
    CEP.error = arguments.new$CEP.error,
    method.regression = arguments.new$method.regression,
    maxiter = arguments.new$maxiter,
    tol = arguments.new$tol,
    lower = arguments.new$lower,
    upper = arguments.new$upper,
    method.SE = arguments.new$method.SE,
    nrep.bootstrap = arguments.new$nrep.bootstrap,
    vis = arguments.new$vis
  )

  return(LCPA.updated)
}

#' @describeIn update Update method for \code{LTA} objects
#' @importFrom utils modifyList
#' @export
update.LTA <- function(object, ...) {
  arguments.current <- object$arguments
  arguments.new <- .update.arguments(
    arguments.current, list(...), LTA, "LTA"
  )

  LTA.updated <- LTA(
    responses = arguments.new$responses,
    L = arguments.new$L,
    type.analysis = arguments.new$type.analysis,
    type.model = arguments.new$type.model,
    covariates = arguments.new$covariates,
    covariates.time.cross = arguments.new$covariates.time.cross,
    ref.class = arguments.new$ref.class,
    dependent.variables = arguments.new$dependent.variables,
    family = arguments.new$family,
    dependent.variable.structure = arguments.new$dependent.variable.structure,
    dependent.variable.time = arguments.new$dependent.variable.time,
    dependent.variable.time.cross = arguments.new$dependent.variable.time.cross,
    method.model = arguments.new$method.model,
    step1.pool = arguments.new$step1.pool,
    control.model = arguments.new$control.model,
    control.EM = arguments.new$control.EM,
    control.Mplus = arguments.new$control.Mplus,
    control.NNE = arguments.new$control.NNE,
    control.Rmixmod = arguments.new$control.Rmixmod,
    method.3step = arguments.new$method.3step,
    CEP.error = arguments.new$CEP.error,
    CEP.time.cross = arguments.new$CEP.time.cross,
    method.regression = arguments.new$method.regression,
    maxiter = arguments.new$maxiter,
    tol = arguments.new$tol,
    lower = arguments.new$lower,
    upper = arguments.new$upper,
    method.SE = arguments.new$method.SE,
    nrep.bootstrap = arguments.new$nrep.bootstrap,
    vis = arguments.new$vis
  )

  return(LTA.updated)
}

#' @describeIn update Update method for \code{sim.LCA} objects
#' @importFrom utils modifyList
#' @export
update.sim.LCA <- function(object, ...) {
  arguments.current <- object$arguments
  arguments.new <- .update.arguments(
    arguments.current, list(...), sim.LCA, "sim.LCA"
  )

  sim.updated <- sim.LCA(
    N = arguments.new$N,
    I = arguments.new$I,
    L = arguments.new$L,
    poly.value = arguments.new$poly.value,
    IQ = arguments.new$IQ,
    distribution = arguments.new$distribution,
    params = arguments.new$params,
    is.sort=arguments.new$is.sort
  )
  return(sim.updated)
}

#' @describeIn update Update method for \code{sim.LPA} objects
#' @importFrom utils modifyList
#' @export
update.sim.LPA <- function(object, ...) {
  arguments.current <- object$arguments
  arguments.new <- .update.arguments(
    arguments.current, list(...), sim.LPA, "sim.LPA"
  )

  sim.updated <- sim.LPA(
    N = arguments.new$N,
    I = arguments.new$I,
    L = arguments.new$L,
    constraint = arguments.new$constraint,
    distribution = arguments.new$distribution,
    mean.range = arguments.new$mean.range,
    covs.range = arguments.new$covs.range,
    params = arguments.new$params,
    is.sort=arguments.new$is.sort
  )
  return(sim.updated)
}

#' @describeIn update Update method for \code{sim.LTA} objects
#' @importFrom utils modifyList
#' @export
update.sim.LTA <- function(object, ...) {
  arguments.current <- object$arguments
  arguments.new <- .update.arguments(
    arguments.current, list(...), sim.LTA, "sim.LTA"
  )

  sim.updated <- sim.LTA(
    N = arguments.new$N,
    I = arguments.new$I,
    L = arguments.new$L,
    times = arguments.new$times,
    type = arguments.new$type,
    distribution = arguments.new$distribution,
    constraint = arguments.new$constraint,
    poly.value = arguments.new$poly.value,
    IQ = arguments.new$IQ,
    mean.range = arguments.new$mean.range,
    covs.range = arguments.new$covs.range,
    params = arguments.new$params,
    is.sort = arguments.new$is.sort,
    rate = arguments.new$rate,
    covariates = arguments.new$covariates,
    ref.class = arguments.new$ref.class,
    beta = arguments.new$beta,
    gamma = arguments.new$gamma
  )
  return(sim.updated)
}
